spring.application.name=TrustBridge

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/trustbridge
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update

stripe.api.secret-key=${STRIPE_SECRET_KEY:sk_test_mock}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.error.include-message=always

# Disable Default Security during initial dev
spring.security.user.name=admin
spring.security.user.password=admin
